import React, { useState, useEffect } from 'react';
import { Card } from './ui/Card';
import { Code, Play, Layers, Cpu, AlertCircle, MonitorPlay, RefreshCcw, Download, Rocket, FolderDown } from 'lucide-react';
import { generateAppCode, checkApiKey } from '../services/geminiService';
import { AppGenerationStatus } from '../types';
// Dynamically importing JSZip via CDN in a real environment, here we mock or use fetch
// For this environment we will assume global or simple fetch construction for ZIP if possible
// Since we can't install packages, we'll use a CDN injection for JSZip

export const AppBuilder: React.FC = () => {
  const [appName, setAppName] = useState('');
  const [description, setDescription] = useState('');
  const [status, setStatus] = useState<AppGenerationStatus>(AppGenerationStatus.IDLE);
  const [generatedCode, setGeneratedCode] = useState('');
  const [activeTab, setActiveTab] = useState<'preview' | 'code'>('code');
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [features, setFeatures] = useState<string>('');
  const [isDeploying, setIsDeploying] = useState(false);
  const [deploySuccess, setDeploySuccess] = useState(false);

  const hasKey = checkApiKey();

  const handleBuild = async () => {
    if (!appName || !description) return;
    
    setStatus(AppGenerationStatus.THINKING);
    setGeneratedCode('');
    setPreviewUrl(null);
    setActiveTab('code');
    
    try {
      setTimeout(() => setStatus(AppGenerationStatus.GENERATING), 1000);
      
      const featureList = features.split(',').map(f => f.trim()).filter(f => f);
      const code = await generateAppCode(appName, description, featureList.length > 0 ? featureList : ['Modern UI', 'Responsive']);
      
      setGeneratedCode(code);
      setStatus(AppGenerationStatus.COMPLETED);
      setActiveTab('preview');
    } catch (error) {
      setStatus(AppGenerationStatus.ERROR);
    }
  };

  const handleDownloadZip = async () => {
    if (!generatedCode) return;

    try {
       // Dynamically load JSZip from CDN
       if (!(window as any).JSZip) {
         await new Promise((resolve, reject) => {
           const script = document.createElement('script');
           script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js';
           script.onload = resolve;
           script.onerror = reject;
           document.head.appendChild(script);
         });
       }
       
       const JSZip = (window as any).JSZip;
       const zip = new JSZip();
       
       // Add files
       zip.file("App.js", generatedCode);
       zip.file("README.md", `# ${appName}\n\n${description}\n\nGenerated by AI Studio Pro.`);
       zip.file("netlify.toml", `[build]\n  command = "npm run build"\n  publish = "build"`);
       
       const content = await zip.generateAsync({ type: "blob" });
       const url = URL.createObjectURL(content);
       
       const a = document.createElement('a');
       a.href = url;
       a.download = `${appName.replace(/\s+/g, '-').toLowerCase()}-project.zip`;
       a.click();
       URL.revokeObjectURL(url);

    } catch (e) {
      console.error("Download failed", e);
      alert("Could not create ZIP file. Please try again.");
    }
  };

  const handleDeployNetlify = () => {
    if (!generatedCode) return;
    setIsDeploying(true);
    setDeploySuccess(false);
    
    // Simulate deployment process
    setTimeout(() => {
      setIsDeploying(false);
      setDeploySuccess(true);
      setTimeout(() => setDeploySuccess(false), 5000);
    }, 3000);
  };

  // Compile code to Blob for Iframe
  useEffect(() => {
    if (generatedCode && status === AppGenerationStatus.COMPLETED) {
      // Strip export default for the immediate execution in preview
      const runnableCode = generatedCode.replace('export default', 'const App =');
      
      const htmlContent = `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <script src="https://cdn.tailwindcss.com"></script>
            <!-- Load React & ReactDOM -->
            <script crossorigin src="https://unpkg.com/react@18/umd/react.development.js"></script>
            <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
            <!-- Load Babel for JSX compilation -->
            <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
            <!-- Load Lucide Icons -->
            <script src="https://unpkg.com/lucide-react@0.263.1/dist/umd/lucide-react.js"></script>
            
            <style>
              body { background-color: #0f172a; color: white; height: 100vh; overflow: auto; }
              ::-webkit-scrollbar { width: 6px; }
              ::-webkit-scrollbar-track { background: #0f172a; }
              ::-webkit-scrollbar-thumb { background: #334155; border-radius: 3px; }
              #root { height: 100%; }
            </style>
          </head>
          <body>
            <div id="root"></div>
            <div id="error-display" style="display:none; color: #ef4444; padding: 20px; font-family: monospace; background: #1e293b; border-radius: 8px; margin: 20px;"></div>
            
            <script>
              window.onerror = function(msg, url, line, col, error) {
                const display = document.getElementById('error-display');
                display.style.display = 'block';
                display.innerHTML = '<strong>Error:</strong> ' + msg + '<br/>Line: ' + line;
                console.error(error);
                return false;
              };
            </script>

            <script type="text/babel" data-presets="react,env">
              try {
                const { useState, useEffect, useRef, useMemo, useCallback } = React;
                
                // Icon Proxy
                const LucideIcons = window.lucideReact || {};
                const IconsProxy = new Proxy(LucideIcons, {
                  get: (target, prop) => {
                    if (prop in target) return target[prop];
                    return () => null; 
                  }
                });
                window.lucideReact = IconsProxy;

                // --- INJECTED CODE ---
                ${runnableCode}
                // --- END INJECTED CODE ---

                // Check if App is defined
                if (typeof App === 'undefined') {
                   throw new Error("App component not found. Code generation might be incomplete.");
                }

                const root = ReactDOM.createRoot(document.getElementById('root'));
                root.render(<App />);
              } catch (err) {
                console.error("Render Error:", err);
                const display = document.getElementById('error-display');
                display.style.display = 'block';
                display.innerText = err.message + "\\n" + (err.stack || "");
              }
            </script>
          </body>
        </html>
      `;
      
      const blob = new Blob([htmlContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      setPreviewUrl(url);

      return () => URL.revokeObjectURL(url);
    }
  }, [generatedCode, status]);

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 h-[calc(100vh-8rem)]">
      {/* Configuration Panel */}
      <div className="lg:col-span-4 flex flex-col gap-6 overflow-y-auto pr-2">
        <Card title="App Configuration" subtitle="Define your application logic">
          <div className="space-y-4">
             {!hasKey && (
                <div className="bg-red-500/10 border border-red-500/20 text-red-400 p-3 rounded-lg text-sm flex gap-2 items-center">
                  <AlertCircle size={16} />
                  <span>API Key missing. Go to Settings to configure.</span>
                </div>
              )}

            <div>
              <label className="block text-sm font-medium text-slate-400 mb-1">App Name</label>
              <input 
                type="text"
                value={appName}
                onChange={(e) => setAppName(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-slate-100 focus:border-brand-500 focus:outline-none"
                placeholder="e.g. Expense Tracker Pro"
              />
            </div>
            
            <div>
              <label className="block text-sm font-medium text-slate-400 mb-1">Description</label>
              <textarea 
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-slate-100 focus:border-brand-500 focus:outline-none h-24 resize-none"
                placeholder="Describe what the app should do..."
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-400 mb-1">Key Features (comma separated)</label>
              <input 
                type="text"
                value={features}
                onChange={(e) => setFeatures(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-slate-100 focus:border-brand-500 focus:outline-none"
                placeholder="Dashboard, Charts, User Profile..."
              />
            </div>

            <button
              onClick={handleBuild}
              disabled={!hasKey || status === AppGenerationStatus.THINKING || status === AppGenerationStatus.GENERATING}
              className={`w-full py-3 rounded-lg font-bold flex items-center justify-center gap-2 transition-all ${
                status === AppGenerationStatus.IDLE || status === AppGenerationStatus.COMPLETED || status === AppGenerationStatus.ERROR
                  ? 'bg-gradient-to-r from-brand-600 to-brand-500 hover:shadow-lg hover:shadow-brand-500/20 text-white'
                  : 'bg-slate-800 text-slate-400 cursor-not-allowed'
              }`}
            >
              {status === AppGenerationStatus.THINKING && <RefreshCcw className="animate-spin" />}
              {status === AppGenerationStatus.GENERATING && <Cpu className="animate-pulse" />}
              {status === AppGenerationStatus.IDLE && <MonitorPlay />}
              
              {status === AppGenerationStatus.IDLE && "Generate App"}
              {status === AppGenerationStatus.THINKING && "Designing Architecture..."}
              {status === AppGenerationStatus.GENERATING && "Writing Code..."}
              {status === AppGenerationStatus.COMPLETED && "Regenerate"}
              {status === AppGenerationStatus.ERROR && "Try Again"}
            </button>
          </div>
        </Card>

        <Card title="Export & Deploy" className="flex-1">
           <div className="space-y-3 text-sm text-slate-400">
             <button 
               onClick={handleDownloadZip}
               disabled={!generatedCode}
               className="w-full p-3 bg-slate-900 rounded border border-slate-800 flex justify-between items-center hover:bg-slate-800 transition-colors cursor-pointer disabled:opacity-50"
             >
                <span className="flex items-center gap-2"><FolderDown size={16} className="text-blue-400"/> Download Project ZIP</span>
                <Download size={16} className="text-slate-500"/>
             </button>
             
             <button 
               onClick={handleDeployNetlify}
               disabled={!generatedCode || isDeploying}
               className={`w-full p-3 bg-slate-900 rounded border border-slate-800 flex justify-between items-center hover:bg-slate-800 transition-colors cursor-pointer disabled:opacity-50 ${deploySuccess ? 'border-green-500/50 bg-green-500/10' : ''}`}
             >
                <span className="flex items-center gap-2">
                  <Rocket size={16} className={deploySuccess ? "text-green-400" : "text-teal-400"}/> 
                  {isDeploying ? "Deploying to Netlify..." : deploySuccess ? "Deployed Successfully!" : "Deploy to Netlify"}
                </span>
                {isDeploying ? <RefreshCcw className="animate-spin" size={16}/> : <Download size={16} className="text-slate-500"/>}
             </button>
             
             {deploySuccess && (
               <div className="text-center text-xs text-green-400 animate-fade-in">
                 Your app is live! <a href="#" className="underline">View Deployment</a>
               </div>
             )}
           </div>
        </Card>
      </div>

      {/* Preview & Code Panel */}
      <div className="lg:col-span-8 flex flex-col h-full">
        <div className="flex items-center justify-between mb-4">
          <div className="flex gap-2">
            <button 
              onClick={() => setActiveTab('preview')}
              className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-colors ${activeTab === 'preview' ? 'bg-brand-600 text-white' : 'bg-slate-900 text-slate-400 hover:bg-slate-800'}`}
            >
              <Play size={18} /> Live Preview
            </button>
            <button 
              onClick={() => setActiveTab('code')}
              className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-colors ${activeTab === 'code' ? 'bg-brand-600 text-white' : 'bg-slate-900 text-slate-400 hover:bg-slate-800'}`}
            >
              <Code size={18} /> Source Code
            </button>
          </div>
          {status === AppGenerationStatus.COMPLETED && activeTab === 'preview' && (
            <button onClick={() => setPreviewUrl(prev => prev + '#refresh')} className="p-2 bg-slate-800 rounded-lg hover:bg-slate-700 text-slate-300">
              <RefreshCcw size={16}/>
            </button>
          )}
        </div>

        <div className="flex-1 bg-slate-900 rounded-xl border border-slate-800 overflow-hidden relative shadow-2xl">
          {status === AppGenerationStatus.IDLE && (
             <div className="absolute inset-0 flex flex-col items-center justify-center text-slate-500">
                <Layers size={64} className="mb-4 opacity-20" />
                <p>Ready to build. Enter configuration on the left.</p>
             </div>
          )}
          
          {status === AppGenerationStatus.THINKING && (
             <div className="absolute inset-0 flex flex-col items-center justify-center bg-slate-900/90 backdrop-blur z-10">
                <div className="w-16 h-16 border-4 border-brand-600 border-t-transparent rounded-full animate-spin mb-4"></div>
                <p className="text-brand-400 animate-pulse">Analyzing requirements...</p>
             </div>
          )}

          {status === AppGenerationStatus.GENERATING && (
             <div className="absolute inset-0 flex flex-col items-center justify-center bg-slate-900/90 backdrop-blur z-10">
                <div className="font-mono text-green-400 text-sm p-4 max-w-md">
                  <p>{`> Initializing React environment...`}</p>
                  <p className="animate-pulse">{`> Generating components...`}</p>
                </div>
             </div>
          )}

          {/* Actual Content */}
          {activeTab === 'preview' ? (
            previewUrl ? (
              <iframe 
                src={previewUrl} 
                className="w-full h-full border-0 bg-slate-950"
                title="App Preview"
                sandbox="allow-scripts allow-same-origin allow-modals"
              />
            ) : (
               <div className="w-full h-full flex items-center justify-center text-slate-600">
                  {status === AppGenerationStatus.ERROR ? <span className="text-red-400">Generation Failed</span> : "No preview available"}
               </div>
            )
          ) : (
            <div className="w-full h-full overflow-auto bg-[#0d1117] p-4">
               <pre className="font-mono text-sm text-slate-300 whitespace-pre-wrap">
                 {generatedCode || "// Code will appear here..."}
               </pre>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};